version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.16.0
        steps:
            - checkout
            - run:
                  name: installing things 
                  command: npm install ; npm install puppeteer ; npm install --save-dev coveralls mocha-lcov-reporter
            - run:
                  name: running tests & coverage
                  command: npm run test ; npm run coveralls
                  timeout: 60000