version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.16.0
        steps:
            - checkout
            - run:
                  name: installing npm things 
                  command: npm install ; npm install puppeteer ; npm install --save-dev coveralls mocha-lcov-reporter
            - run:
                  name: installing puppeteer things
                  command: sudo apt-get update ; sudo apt-get install -y
            - run:
                  name: running tests
                  command: npm run test
                  timeout: 400000
            - run:
                  name: running coverage
                  command: npm run coveralls
                  timeout: 400000