version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.16.0
        working_directory: ~
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "public/package.json" }}
                      - v1-dependencies-
            - run:
                  name: Install Dependencies
                  command: npm install
            - save_cache:
                  key: v1-npm-deps-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: Build
                  command: npm build
            - run:
                  name: Firebase Deploy
                  command: functions/node_modules/.bin/firebase deploy --token="$FIREBASE_TOKEN"
