version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run:
                  name: installing npm dependencies
                  command: npm install
            - run:
                  name: installing npm & puppeteer
                  command: ls
            # - run:
            #       name: run tests
            #       command: cd public/ ; cd public/ ; cd tests/ ; npm run test